version: '3'

tasks:
  format: deno fmt ./
  default:
    cmds:
    - task: format
    - npm run build
    - builder --source-path ./content --build-path build/ --base-url https://sqlite.fun --serve

      