version: '3'

tasks:
  format:
    cmds:
    - deno fmt content/ functions/
    - deno lint content/ functions/
  default:
    cmds:
    - task: format
    - npm run build
    - builder --source-path ./content --build-path build/ --base-url https://sqlite.fun