on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
        # Fix timestamps
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - name: Install builder
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab the latest version
          repo: jtarchie/builder
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: enable

      - name: Build
        run: |
          builder \
            --source-path ./content/ \
            --build-path ./build/ \
            --base-url https://sqlite.fun

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 945954ae6af55e6e4af004fb7772fdc5
          command: pages deploy --project-name=sqlite-fun
